# Generated by Django 4.1.13 on 2024-08-02 14:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by', models.CharField(default=None, max_length=200)),
                ('file', models.FileField(upload_to='pdfs/')),
                ('file_text', models.TextField(blank=True, default='')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by', models.CharField(default='', max_length=200)),
                ('file', models.FileField(upload_to='pdfs/')),
                ('file_text', models.TextField(blank=True, default='')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=200)),
                ('company', models.CharField(default=None, max_length=200)),
                ('location', models.CharField(default=None, max_length=200)),
                ('logo', models.ImageField(default=None, upload_to='')),
                ('type_of_employment', models.CharField(default=None, max_length=200)),
                ('lowest_monthly_salary_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('highest_monthly_salary_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deadline', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_postings', to='hrcombo.jobpdf')),
            ],
        ),
        migrations.CreateModel(
            name='CandidatePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default=None, max_length=200)),
                ('preferred_location', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('industries', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume_pdf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrcombo.resumepdf')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(default=None, max_length=200)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrcombo.jobposting')),
            ],
        ),
    ]
