# Generated by Django 4.1.13 on 2024-07-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrcombo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('message', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='clerk_id',
            field=models.CharField(default='user_clerk_id', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
