# Generated by Django 4.1.13 on 2024-08-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrcombo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='industries',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
