# Generated by Django 5.0.7 on 2024-08-01 00:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrcombo', '0002_message_remove_user_password_remove_user_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidatePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_location', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('industries', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='pdfs/')),
                ('file_text', models.TextField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResumePDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_by', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='pdfs/')),
                ('file_text', models.TextField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='user',
        ),
        migrations.DeleteModel(
            name='AIModel',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='application',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='application',
            name='score',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='description',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='skills',
        ),
        migrations.AddField(
            model_name='application',
            name='applicant',
            field=models.CharField(default='applicant', max_length=255),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='deadline',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='highest_monthly_salary_usd',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='logo',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='lowest_monthly_salary_usd',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='type_of_employment',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='company',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='location',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='title',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='job_pdf',
            field=models.ForeignKey(default='job-pdf-id', on_delete=django.db.models.deletion.CASCADE, to='hrcombo.jobpdf'),
        ),
        migrations.AddField(
            model_name='candidatepreference',
            name='resume_pdf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrcombo.resumepdf'),
        ),
        migrations.DeleteModel(
            name='ActivityLog',
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
