# Generated by Django 5.0.7 on 2024-08-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrcombo', '0003_candidatepreference_jobpdf_resumepdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpdf',
            name='file_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='resumepdf',
            name='file_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
